const profiles = [
  {
    id: "minimax-cn",
    displayName: "MiniMax CN",
    group: "china",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.minimaxi.com/v1",
    defaultModel: "MiniMax-M2.7",
    suggestedModels: ["MiniMax-M2.7"],
    note: {
      "zh-CN": "MiniMax 中国区；支持按量 Key 与 Token Plan Key。",
      en: "MiniMax China; supports pay-as-you-go and Token Plan keys.",
    },
  },
  {
    id: "minimax-global",
    displayName: "MiniMax Global",
    group: "global",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.minimax.io/v1",
    defaultModel: "MiniMax-M2.7",
    suggestedModels: ["MiniMax-M2.7"],
    note: { "zh-CN": "MiniMax 国际区。", en: "MiniMax global endpoint." },
  },
  {
    id: "openai",
    displayName: "OpenAI",
    group: "global",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-5.6-luna",
    suggestedModels: ["gpt-5.6-luna", "gpt-5.6-terra", "gpt-5.6-sol"],
    note: { "zh-CN": "OpenAI 官方 API。", en: "Official OpenAI API." },
  },
  {
    id: "anthropic",
    displayName: "Anthropic",
    group: "global",
    protocol: "anthropic",
    defaultBaseUrl: "https://api.anthropic.com/v1",
    defaultModel: "claude-sonnet-5",
    suggestedModels: ["claude-sonnet-5", "claude-haiku-4-5", "claude-opus-5"],
    note: { "zh-CN": "Claude 官方 Messages API（原生协议）。", en: "Official Claude Messages API (native protocol)." },
  },
  {
    id: "gemini",
    displayName: "Google Gemini",
    group: "global",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    defaultModel: "gemini-3.6-flash",
    suggestedModels: ["gemini-3.6-flash", "gemini-3.5-flash", "gemini-3.5-flash-lite"],
    note: { "zh-CN": "Google 官方 OpenAI 兼容接口。", en: "Google's official OpenAI-compatible endpoint." },
  },
  {
    id: "xai",
    displayName: "xAI",
    group: "global",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-4.5",
    suggestedModels: ["grok-4.5", "grok-4-latest"],
    note: { "zh-CN": "xAI 官方 API。", en: "Official xAI API." },
  },
  {
    id: "openrouter",
    displayName: "OpenRouter",
    group: "router",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "~openai/gpt-latest",
    suggestedModels: ["~openai/gpt-latest", "~anthropic/claude-sonnet-latest", "~moonshotai/kimi-latest"],
    note: { "zh-CN": "用一个 Key 访问和路由数百个模型。", en: "Access and route hundreds of models with one key." },
  },
  {
    id: "vercel-ai-gateway",
    displayName: "Vercel AI Gateway",
    group: "router",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://ai-gateway.vercel.sh/v1",
    defaultModel: "anthropic/claude-sonnet-4.6",
    suggestedModels: ["anthropic/claude-sonnet-4.6", "openai/gpt-5.4-mini", "xai/grok-4.1-fast-reasoning"],
    note: { "zh-CN": "Vercel 统一路由、预算与回退；模型名使用 creator/model。", en: "Vercel routing, budgets, and fallbacks; model IDs use creator/model." },
  },
  {
    id: "perplexity",
    displayName: "Perplexity",
    group: "router",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.perplexity.ai/v1",
    defaultModel: "sonar",
    suggestedModels: ["sonar", "sonar-pro", "openai/gpt-5-mini"],
    note: { "zh-CN": "Perplexity Sonar 与 Agent 模型；回答可使用联网检索。", en: "Perplexity Sonar and Agent models with optional web-grounded answers." },
  },
  {
    id: "huggingface",
    displayName: "Hugging Face",
    group: "router",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://router.huggingface.co/v1",
    defaultModel: "openai/gpt-oss-120b:fastest",
    suggestedModels: ["openai/gpt-oss-120b:fastest", "deepseek-ai/DeepSeek-R1:fastest"],
    note: { "zh-CN": "Hugging Face Inference Providers 路由。", en: "Hugging Face Inference Providers routing." },
  },
  {
    id: "deepseek",
    displayName: "DeepSeek",
    group: "china",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-v4-flash",
    suggestedModels: ["deepseek-v4-flash", "deepseek-v4-pro"],
    note: { "zh-CN": "DeepSeek 官方 API。", en: "Official DeepSeek API." },
  },
  {
    id: "qwen-cn",
    displayName: "Alibaba Qwen · China",
    group: "china",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen-plus",
    suggestedModels: ["qwen-plus", "qwen3.8-max", "qwen3.7-plus"],
    note: { "zh-CN": "阿里云百炼中国区；可覆盖为业务空间专属地址。", en: "Alibaba Model Studio China; workspace endpoints can override the Base URL." },
  },
  {
    id: "qwen-global",
    displayName: "Alibaba Qwen · Global",
    group: "global",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen-plus",
    suggestedModels: ["qwen-plus", "qwen3.8-max", "qwen3.7-plus"],
    note: { "zh-CN": "阿里云百炼国际区；Key 与区域必须匹配。", en: "Alibaba Model Studio global; the key must match the region." },
  },
  {
    id: "zai-global",
    displayName: "Z.AI",
    group: "global",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.z.ai/api/paas/v4",
    defaultModel: "glm-5.1",
    suggestedModels: ["glm-5.1", "glm-4.7"],
    note: { "zh-CN": "Z.AI 国际区通用 API；Coding Plan 请覆盖专用 Base URL。", en: "Z.AI global API; override the Base URL for a Coding Plan." },
  },
  {
    id: "zai-cn",
    displayName: "智谱 BigModel",
    group: "china",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultModel: "glm-5.1",
    suggestedModels: ["glm-5.1", "glm-4.7"],
    note: { "zh-CN": "智谱中国区通用 API；Coding Plan 请覆盖专用 Base URL。", en: "Zhipu BigModel China API; override the Base URL for a Coding Plan." },
  },
  {
    id: "siliconflow",
    displayName: "SiliconFlow",
    group: "china",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.siliconflow.com/v1",
    defaultModel: "zai-org/GLM-5.1",
    suggestedModels: ["zai-org/GLM-5.1"],
    note: { "zh-CN": "SiliconFlow 国际接口。", en: "SiliconFlow global endpoint." },
  },
  {
    id: "groq",
    displayName: "Groq",
    group: "inference",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "openai/gpt-oss-120b",
    suggestedModels: ["openai/gpt-oss-120b", "llama-3.1-8b-instant"],
    note: { "zh-CN": "GroqCloud 高速推理。", en: "High-speed inference on GroqCloud." },
  },
  {
    id: "fireworks",
    displayName: "Fireworks AI",
    group: "inference",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/llama-v3p1-8b-instruct",
    suggestedModels: ["accounts/fireworks/models/llama-v3p1-8b-instruct", "accounts/fireworks/models/kimi-k2p5"],
    note: { "zh-CN": "Fireworks AI 托管与按需部署模型。", en: "Serverless and on-demand models on Fireworks AI." },
  },
  {
    id: "mistral",
    displayName: "Mistral AI",
    group: "inference",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-small-latest",
    suggestedModels: ["mistral-small-latest", "mistral-large-latest"],
    note: { "zh-CN": "Mistral 官方 API。", en: "Official Mistral API." },
  },
  {
    id: "together",
    displayName: "Together AI",
    group: "inference",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.together.ai/v1",
    defaultModel: "openai/gpt-oss-20b",
    suggestedModels: ["openai/gpt-oss-20b", "meta-llama/Llama-3.3-70B-Instruct-Turbo"],
    note: { "zh-CN": "Together AI 开源模型推理。", en: "Open-model inference on Together AI." },
  },
  {
    id: "cerebras",
    displayName: "Cerebras",
    group: "inference",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://api.cerebras.ai/v1",
    defaultModel: "zai-glm-4.7",
    suggestedModels: ["zai-glm-4.7", "gpt-oss-120b"],
    note: { "zh-CN": "Cerebras 高速推理。", en: "High-speed inference on Cerebras." },
  },
  {
    id: "nvidia-nim",
    displayName: "NVIDIA NIM",
    group: "inference",
    protocol: "openai-compatible",
    defaultBaseUrl: "https://integrate.api.nvidia.com/v1",
    defaultModel: "openai/gpt-oss-20b",
    suggestedModels: ["openai/gpt-oss-20b", "openai/gpt-oss-120b", "moonshotai/kimi-k2-thinking"],
    note: { "zh-CN": "NVIDIA 托管 NIM 原型接口。", en: "NVIDIA hosted NIM prototype endpoint." },
  },
  {
    id: "ollama",
    displayName: "Ollama",
    group: "local",
    protocol: "openai-compatible",
    defaultBaseUrl: "http://127.0.0.1:11434/v1",
    defaultModel: "",
    suggestedModels: ["qwen3:8b", "llama3.2", "gemma3"],
    apiKeyRequired: false,
    note: { "zh-CN": "本机 Ollama；无需 API Key，模型名以本机安装为准。", en: "Local Ollama; no API key required, and model names depend on local installs." },
  },
  {
    id: "lm-studio",
    displayName: "LM Studio",
    group: "local",
    protocol: "openai-compatible",
    defaultBaseUrl: "http://127.0.0.1:1234/v1",
    defaultModel: "",
    suggestedModels: [],
    apiKeyRequired: false,
    note: { "zh-CN": "本机 LM Studio Server；无需 API Key。", en: "Local LM Studio Server; no API key required." },
  },
  {
    id: "openai-compatible",
    displayName: "Custom OpenAI-compatible",
    group: "custom",
    protocol: "openai-compatible",
    defaultBaseUrl: "",
    defaultModel: "",
    suggestedModels: [],
    note: { "zh-CN": "填写兼容 /chat/completions 的地址；支持 HTTPS 与本机 HTTP。", en: "Enter a /chat/completions-compatible endpoint; HTTPS and local HTTP are supported." },
  },
];

function freezeProfile(profile) {
  return Object.freeze({
    ...profile,
    aliases: Object.freeze([...(profile.aliases || [])]),
    suggestedModels: Object.freeze([...(profile.suggestedModels || [])]),
    apiKeyRequired: profile.apiKeyRequired !== false,
    baseUrlEditable: profile.baseUrlEditable !== false,
    modelDiscovery: profile.modelDiscovery !== false,
    note: Object.freeze({ ...(profile.note || {}) }),
  });
}

export const PROVIDER_CATALOG = Object.freeze(profiles.map(freezeProfile));
const profilesById = new Map(PROVIDER_CATALOG.map(profile => [profile.id, profile]));

export function getProviderProfile(id) {
  return profilesById.get(String(id || "").trim()) || null;
}

export function isKnownProvider(id) {
  return profilesById.has(String(id || "").trim());
}

export function providerNote(profile, locale = "en") {
  if (!profile) return "";
  return profile.note?.[locale] || profile.note?.en || profile.note?.["zh-CN"] || "";
}
